name: vivino
channels:
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - plotly
  - python=3.8
  - scikit-learn=0.24
  - seaborn
  - statsmodels=0.14.0
  - python-kaleido
